import os
from pathlib import Path
from typing import Any

from dotenv import load_dotenv
from google import genai
from google.genai import types
from PIL import Image

from app.data_sources.sentinel_provider import SentinelProvider
from app.tools.base import BaseTool


load_dotenv()


class SceneCaptionTool(BaseTool):
    """
    Download or reuse a real Sentinel-2 satellite image and
    analyze it using Gemini Vision.

    Priority:
    1. Use explicitly provided local image
    2. Use image produced by a dependency task
    3. Download a new Sentinel-2 image using bbox
    """

    name = "scene_caption"

    description = (
        "Analyze a real Sentinel-2 satellite image using "
        "Gemini Vision and describe visible Earth Observation "
        "features and spatial patterns."
    )

    def __init__(self) -> None:
        self.gemini_api_key = (
            os.getenv("GOOGLE_API_KEY")
            or os.getenv("GEMINI_API_KEY")
        )

        if not self.gemini_api_key:
            raise ValueError(
                "GOOGLE_API_KEY or GEMINI_API_KEY is missing. "
                "Add one API key to your .env file."
            )

        self.gemini_model = os.getenv(
            "GEMINI_MODEL",
            "gemini-3.6-flash",
        )

        self.client = genai.Client(
            api_key=self.gemini_api_key
        )

        self.sentinel_provider = SentinelProvider()

    # =========================================================
    # GET IMAGE
    # =========================================================

    def _get_image_path(
        self,
        parameters: dict[str, Any],
    ) -> tuple[str, dict[str, Any] | None]:
        """
        Get an image using this priority:

        1. Existing local image path from image_urls
        2. AFTER image generated by dependency task
        3. Download a new Sentinel-2 image using bbox
        """

        image_urls = parameters.get(
            "image_urls",
            [],
        )

        # -----------------------------------------------------
        # OPTION 1: EXISTING LOCAL IMAGE
        # -----------------------------------------------------

        if image_urls:

            if not isinstance(
                image_urls,
                list,
            ):
                raise ValueError(
                    "'image_urls' must be a list."
                )

            image_path = Path(
                image_urls[0]
            )

            if not image_path.exists():
                raise FileNotFoundError(
                    "Image file not found: "
                    f"{image_urls[0]}"
                )

            return str(image_path), None

        # -----------------------------------------------------
        # OPTION 2: USE IMAGE FROM DEPENDENCY RESULT
        # -----------------------------------------------------

        dependency_results = parameters.get(
            "dependency_results",
            {},
        )

        if isinstance(
            dependency_results,
            dict,
        ):

            for dependency in (
                dependency_results.values()
            ):

                if not isinstance(
                    dependency,
                    dict,
                ):
                    continue

                result = dependency.get(
                    "result",
                    {},
                )

                if not isinstance(
                    result,
                    dict,
                ):
                    continue

                # Prefer the AFTER image because this is the
                # most recent observation from change analysis.
                after_image = result.get(
                    "after_image"
                )

                if after_image:

                    image_path = Path(
                        after_image
                    )

                    if image_path.exists():

                        metadata = result.get(
                            "after_sentinel"
                        )

                        return (
                            str(image_path),
                            metadata,
                        )

                # Fallback to before image if after image is
                # unavailable.
                before_image = result.get(
                    "before_image"
                )

                if before_image:

                    image_path = Path(
                        before_image
                    )

                    if image_path.exists():

                        metadata = result.get(
                            "before_sentinel"
                        )

                        return (
                            str(image_path),
                            metadata,
                        )

        # -----------------------------------------------------
        # OPTION 3: DOWNLOAD FROM BBOX
        # -----------------------------------------------------

        bbox = parameters.get("bbox")

        if bbox:

            if (
                not isinstance(
                    bbox,
                    list,
                )
                or len(bbox) != 4
            ):
                raise ValueError(
                    "bbox must contain exactly 4 values: "
                    "[min_lon, min_lat, "
                    "max_lon, max_lat]"
                )

            result = (
                self.sentinel_provider
                .download_best_sentinel2_image(
                    bbox=bbox,
                    output_path=(
                        "data/"
                        "latest_scene_sentinel2.png"
                    ),
                    lookback_days=180,
                    max_cloud_coverage=80.0,
                )
            )

            return (
                result["image_path"],
                result,
            )

        raise ValueError(
            "Provide either 'image_urls', dependency results, "
            "or 'bbox'."
        )

    # =========================================================
    # ANALYZE IMAGE WITH GEMINI
    # =========================================================

    def _analyze_image(
        self,
        image_path: str,
        user_question: str | None = None,
    ) -> str:
        """
        Send the satellite image to Gemini Vision.
        """

        image = Image.open(
            image_path
        ).convert("RGB")

        prompt = """
You are an expert Earth Observation and remote sensing analyst.

Analyze this real Sentinel-2 satellite image carefully.

Describe only what is visually observable in the image.

Analyze the following:

1. Overall landscape and land-cover patterns
2. Vegetation and forest cover
3. Agricultural land and crop or field patterns
4. Bare soil or dry areas
5. Urban or built-up areas
6. Roads or visible linear infrastructure
7. Rivers, lakes, reservoirs, or other water bodies
8. Terrain and spatial distribution patterns

Important rules:

- Do not invent precise place names.
- Do not invent events, dates, or facts that cannot be
  determined from the image.
- Do not claim that temporal change occurred from this
  single image alone.
- Clearly distinguish observations from uncertainty.
- Do not claim exact measurements unless supported by
  provided metadata or image data.
- Do not say that two images are required if you are only
  asked to analyze the currently provided image.
- Provide a clear, structured, and useful Earth Observation
  analysis.

Use headings and concise bullet points where appropriate.
"""

        if user_question:

            prompt += (
                "\n\nThe user's query is:\n"
                f"{user_question}\n\n"
                "Answer the relevant parts of the query using "
                "only what is visually observable in this image."
            )

        try:

            response = (
                self.client.models.generate_content(
                    model=self.gemini_model,
                    contents=[
                        prompt,
                        image,
                    ],
                    config=types.GenerateContentConfig(
                        temperature=0.2,
                    ),
                )
            )

        except Exception as error:

            raise RuntimeError(
                "Gemini image analysis failed: "
                f"{error}"
            ) from error

        if not response.text:

            raise RuntimeError(
                "Gemini did not return an image analysis."
            )

        return response.text.strip()

    # =========================================================
    # RUN COMPLETE TOOL
    # =========================================================

    def run(
        self,
        parameters: dict[str, Any],
    ) -> dict[str, Any]:
        """
        Run the complete scene caption pipeline.

        Priority:

        1. Analyze an existing local image
        2. Analyze an image from a dependency task
        3. Download and analyze a Sentinel-2 image using bbox
        """

        # -----------------------------------------------------
        # GET USER QUESTION
        # -----------------------------------------------------

        user_question = (
            parameters.get("question")
            or parameters.get("query")
        )

        # -----------------------------------------------------
        # GET OR DOWNLOAD IMAGE
        # -----------------------------------------------------

        image_path, sentinel_metadata = (
            self._get_image_path(
                parameters
            )
        )

        # -----------------------------------------------------
        # GET IMAGE DIMENSIONS
        # -----------------------------------------------------

        with Image.open(
            image_path
        ) as opened_image:

            image = opened_image.convert(
                "RGB"
            )

            width, height = image.size

        # -----------------------------------------------------
        # ANALYZE IMAGE WITH GEMINI
        # -----------------------------------------------------

        caption = self._analyze_image(
            image_path=image_path,
            user_question=user_question,
        )

        # -----------------------------------------------------
        # BUILD RESPONSE
        # -----------------------------------------------------

        result = {
            "tool": self.name,
            "status": "success",
            "caption": caption,
            "image": str(image_path),
            "width": width,
            "height": height,
        }

        # -----------------------------------------------------
        # ADD SENTINEL METADATA
        # -----------------------------------------------------

        if sentinel_metadata:

            result["sentinel"] = {
                "product_id": (
                    sentinel_metadata.get(
                        "product_id"
                    )
                ),
                "datetime": (
                    sentinel_metadata.get(
                        "datetime"
                    )
                ),
                "cloud_cover": (
                    sentinel_metadata.get(
                        "cloud_cover"
                    )
                ),
            }

        return result