AGENT_STATUS_PENDING = "pending"
AGENT_STATUS_RUNNING = "running"
AGENT_STATUS_SUCCESS = "success"
AGENT_STATUS_FAILED = "failed"

TASK_STATUS_PENDING = "pending"
TASK_STATUS_COMPLETED = "completed"
TASK_STATUS_FAILED = "failed"

DEFAULT_CONFIDENCE = 0.75